### ISSUE TITLE
ReferenceError: document is not defined

### ISSUE THREAD

**Issue by HugoHeneault** [danielstgt/svg-vue3#2]
Hello there, 

I'm using https://github.com/danielstgt/laravel-mix-svg-vue and it works well (thanks)

But in SSR mode (Laravel + Inertia) I have the following error

```
[Vue warn]: Unhandled error during execution of render function 
  at <SvgVue icon="add" class="w-3 mr-2" >
ReferenceError: document is not defined
    at ReactiveEffect.fn (/var/www/html/node_modules/svg-vue3/dist/svg-vue.ssr.js:69:21)
    at ReactiveEffect.run (/var/www/html/node_modules/@vue/reactivity/dist/reactivity.cjs.js:150:25)
    at ComputedRefImpl.get value [as value] (/var/www/html/node_modules/@vue/reactivity/dist/reactivity.cjs.js:1090:39)
    at unref (/var/www/html/node_modules/@vue/reactivity/dist/reactivity.cjs.js:998:29)
    at Object.get (/var/www/html/node_modules/@vue/reactivity/dist/reactivity.cjs.js:1001:37)
    at Proxy.render (/var/www/html/node_modules/svg-vue3/dist/svg-vue.ssr.js:87:72)
    at renderComponentRoot (/var/www/html/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:887:44)
    at renderComponentSubTree (/var/www/html/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:275:51)
    at renderComponentVNode (/var/www/html/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:214:16)
    at renderVNode (/var/www/html/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:310:22)

```

I'm wondering why `document` is called in an `ssr` file?

Thanks for your help.

**Comment by danielstgt** [comment]
Hi @HugoHeneault,

first off, my sincere apologies for the extremely late reply, this issue sat unanswered far longer than it should have. Thank you for the clear report and stack trace; they made the root cause easy to pin down.

The component derived the root `<svg>` element's attributes (`viewBox`, `fill`, etc.) by writing the SVG string into `document.createElement('div')` and reading the attributes back off the DOM node. That parsing ran inside a `computed`, i.e. during render, so under SSR, where there is no `document`, it threw the `ReferenceError` you saw in `svg-vue.ssr.js`. You were right to wonder why `document` was being touched in an SSR file.

**The fix**

The DOM round-trip is replaced with a small string/regex parser that reads the attributes straight from the SVG string. It behaves identically on the server and in the browser, so:

- no `document` is required anymore → SSR (Laravel + Inertia) works,
- server and client produce the same markup → no hydration mismatch,
- the public API is unchanged → it's a non-breaking patch.

Published as `svg-vue3@0.2.3`:

```bash
npm update svg-vue3
```

If you consume it through `laravel-mix-svg-vue`, its `^0.2.1` range picks the fix up automatically on a fresh install. (The Vue 2 sibling `svg-vue@0.2.2` received the same fix, for anyone on that path.)

Thanks again for your patience, and please reopen if anything still misbehaves under SSR.
